# Generated by Django 5.2.8 on 2025-11-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Table label, e.g. R1-T1, 4, Outside-3, etc.', max_length=20, unique=True)),
                ('capicity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('party_size', models.PositiveIntegerField()),
                ('seating_preference', models.CharField(choices=[('NO_PREF', 'No preference'), ('INDOOR', 'Indoor only'), ('OUTDOOR_IF_POSSIBLE', 'Outdoor if possible')], default='NO_PREF', max_length=25)),
                ('notes', models.TextField(blank=True, help_text='Special requests: highchairs, low table, allergies, buggy, etc.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('source', models.CharField(default='ONLINE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tables', models.ManyToManyField(blank=True, help_text='Internal use: assign one or more tables to this reservation.', related_name='reservations', to='reservations.table')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
