# Generated by Django 5.2.8 on 2025-11-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_openinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indoor_capacity', models.PositiveIntegerField(default=42, help_text='Total indoor seats used for capacity calculations.')),
                ('outdoor_capacity', models.PositiveIntegerField(default=54, help_text='Total outdoor seats used for capacity calculations.')),
            ],
            options={
                'verbose_name': 'Restaurant settings',
                'verbose_name_plural': 'Restaurant settings',
            },
        ),
        migrations.AlterModelOptions(
            name='openinghours',
            options={'ordering': ['weekday'], 'verbose_name': 'Opening hour', 'verbose_name_plural': 'Opening hours'},
        ),
    ]
