# Generated by Django 5.2.8 on 2025-11-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_restaurantsettings_alter_openinghours_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='large_group_min_size',
            field=models.PositiveBigIntegerField(default=7, help_text="Minimum party size considered to be a 'large group'. The default number is 7"),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='max_large_groups_indoor',
            field=models.PositiveBigIntegerField(default=2, help_text='Maximum number of overlapping large indoor groups. The default number is 2'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='max_large_groups_outdoor',
            field=models.PositiveBigIntegerField(default=2, help_text='Maximum number of overlapping very large indoor groups. The default number is 2'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='max_party_size_inddor',
            field=models.PositiveIntegerField(default=12, help_text="Maximum party size allowed for 'Indoor' & 'No preference' online bookings. The default number is 12"),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='max_party_size_outdoor',
            field=models.PositiveIntegerField(default=8, help_text="Maximum party size allowed for 'Outdoor' online bookings. The default number is 8"),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='max_very_large_groups_indoor',
            field=models.PositiveBigIntegerField(default=1, help_text='Maximum number of overlapping very large indoor groups. The default number is 1'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='medium_group_max_size',
            field=models.PositiveBigIntegerField(default=6, help_text="Maximum party size considered to be a 'medium group'. The default number is 6"),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='medium_group_min_size',
            field=models.PositiveBigIntegerField(default=5, help_text="Minimum party size considered to be a 'medium group'. The default number is 5"),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='very_large_group_min_size',
            field=models.PositiveBigIntegerField(default=9, help_text="Minimum party size considered to be a 'very large group'. The default number is 9"),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='indoor_capacity',
            field=models.PositiveIntegerField(default=42, help_text='Total indoor seats used for capacity calculations. The default number is 42'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='outdoor_capacity',
            field=models.PositiveIntegerField(default=54, help_text='Total outdoor seats used for capacity calculations. The default number is 54'),
        ),
    ]
