# Generated by Django 5.2.8 on 2025-11-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_restaurantsettings_large_group_min_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantsettings',
            old_name='max_party_size_inddor',
            new_name='max_party_size_indoor',
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='closure_message',
            field=models.TextField(blank=True, help_text='Message shown on the public reservation page when reservations are closed. Leave blank to use a default message.'),
        ),
        migrations.AddField(
            model_name='restaurantsettings',
            name='reservations_open',
            field=models.BooleanField(default=True, help_text='Uncheck this to temporarily close the online reservation form.'),
        ),
    ]
