# Generated by Django 5.2.8 on 2025-11-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_rename_max_party_size_inddor_restaurantsettings_max_party_size_indoor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOpeningDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_open', models.BooleanField(default=True, help_text='Uncheck to trat this date as closed.')),
                ('bookings_open_from', models.DateField(help_text='Date from which online reservations are allowed for this day')),
                ('public_message', models.CharField(blank=True, help_text='Optional short message shown on the reservation page', max_length=255)),
            ],
            options={
                'verbose_name': 'Special opening day',
                'verbose_name_plural': 'Special opening days',
                'ordering': ['date'],
            },
        ),
    ]
