# Generated by Django 5.2.8 on 2025-11-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_specialopeningday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SEATED', 'Seated'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No show'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
    ]
