# Generated by Django 5.2.8 on 2025-11-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialopeningday',
            name='close_time',
            field=models.TimeField(blank=True, help_text='Optional: closing time for this special day.', null=True),
        ),
        migrations.AddField(
            model_name='specialopeningday',
            name='last_res_time',
            field=models.TimeField(blank=True, help_text='Optional: last time a new reservation can start. If blank, close_time will be used.', null=True),
        ),
        migrations.AddField(
            model_name='specialopeningday',
            name='open_time',
            field=models.TimeField(blank=True, help_text='Optional: opening time for this special day. Leave blank to use normal weekday hours.', null=True),
        ),
        migrations.AlterField(
            model_name='specialopeningday',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Uncheck to treat this date as closed.'),
        ),
    ]
