# Generated by Django 5.2.8 on 2025-11-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_specialopeningday_close_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantsettings',
            name='dwell_minutes',
            field=models.PositiveIntegerField(default=90, help_text='Average duration of a reservation /including clean-up/, in minutes. Used for reservation capacity and load calculations.The default time is 90 minutes.'),
        ),
    ]
