# Generated by Django 5.2.8 on 2025-11-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_restaurantsettings_dwell_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='area',
            field=models.CharField(choices=[('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor')], default='INDOOR', help_text='Used for indoor/outdoor stats and assignment', max_length=10),
        ),
        migrations.AddField(
            model_name='table',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to temporarily remove this table from use.'),
        ),
        migrations.AlterField(
            model_name='restaurantsettings',
            name='dwell_minutes',
            field=models.PositiveIntegerField(default=90, help_text='Average duration of a reservation (including clean up time), in minutes. Used for reservation capacity and load calculations. The default time is 90 minutes.'),
        ),
    ]
